#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-4 --primary --mode 1920x1080 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --right-of DP-4
picom -f &
feh --bg-fill ~/wp5104897.jpg &
/home/antonios/.config/polybar/launch.sh

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding		58

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius	 8
